### ISSUE TITLE
v0.0.21 seems to break the use case when KUBERNETES_EXEC_INFO is empty

### ISSUE THREAD

**Issue by yurrriq** [Azure/kubelogin#150] opened 2022-11-15 20:31 UTC
It seems that since https://github.com/Azure/kubelogin/pull/145, `KUBERNETES_EXEC_INFO` is now required. My v0.0.20 workflow now fails with the following.

```bash
export KUBERNETES_EXEC_INFO=""

kubelogin get-token \
    --login devicecode \
    --server-id <AAD server app ID> \
    --client-id <AAD client app ID> \
    --tenant-id <AAD tenant ID> 
    --environment AzurePublicCloud
```

```
Error: cannot convert to ExecCredential: unexpected end of JSON input
```

**Comment by weinong** [comment] 2022-11-15 21:18
@yurrriq what is the version of your kubectl?

**Comment by ITHedgeHog** [comment] 2022-11-16 00:30
@weinong This is happening to me, output from our GitHub action below:

`Run az aks install-cli
WARNING: The detected arch is , would be treated as amd64, which may not match the actual situation due to translation and other reasons. If there is any problem, please download the appropriate binary by yourself.
WARNING: Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/**v1.25.4**/bin/linux/amd64/kubectl"
WARNING: Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
WARNING: The detected arch is , would be treated as amd64, which may not match the actual situation due to translation and other reasons. If there is any problem, please download the appropriate binary by yourself.
WARNING: Downloading client to "/tmp/tmpz8qisgsq/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/**v0.0.21**/kubelogin.zip"
WARNING: Please ensure that /usr/local/bin is in your search PATH, so the `kubelogin` command can be found.`

I'm working around right now by specifying installing v0.0.20 of kubelogin in the action

**Comment by weinong** [comment] 2022-11-16 02:02
@ITHedgeHog , how did you use kubelogin, though? kubectl should have set `KUBERNETES_EXEC_INFO`. While we are fixing this, I'm just curious about how you use it

**Comment by ITHedgeHog** [comment] 2022-11-16 06:02
This is how we invoke kubelogin `kubelogin convert-kubeconfig convert-kubeconfig -l azurecli`

Then we just issue kubectl commands.

**Comment by weinong** [comment] 2022-11-16 17:25
@ITHedgeHog Interesting, I was unable to repro it. Well, it's fixed in v0.0.22. Please give it a try!

**Comment by ITHedgeHog** [comment] 2022-11-16 21:51
Thanks, I'll update one of our Actions and give it a test.

**Comment by wiceywkus** [comment] 2022-11-16 23:29
Using Azure Kubelogin v0.0.22 with this user config:
`
- name: john.doe
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --server-id
      - <serverguid>
      - --client-id
      - <clientidguid>
      - --tenant-id
      - <tenantidguid>
      - --environment
      - AzurePublicCloud
      - --legacy
      command: kubelogin
      env: null
      provideClusterInfo: false
`
Error is:
`
Error: devicelogin is not supported if interactiveMode is 'never'
Unable to connect to the server: getting credentials: exec: executable kubelogin failed with exit code 1
`
Adding
`
      interactiveMode: IfAvailable
`
still results in
`
Error: devicelogin is not supported if interactiveMode is 'never'
Unable to connect to the server: getting credentials: exec: executable kubelogin failed with exit code 1
`
Adding
`
      - --login
      - devicecode
`
still results in
`
Error: devicelogin is not supported if interactiveMode is 'never'
Unable to connect to the server: getting credentials: exec: executable kubelogin failed with exit code 1
`

**Comment by weinong** [comment] 2022-11-17 00:03
@wiceywkus what is your kubectl version?

**Comment by wiceywkus** [comment] 2022-11-17 02:31
```
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"windows/amd64"}
```

**Comment by yurrriq** [comment] 2022-11-17 16:34
> @yurrriq what is the version of your kubectl?

1.25.3 via https://github.com/NixOS/nixpkgs/blob/7f9be6a505a31f88499c5d20d11f98accf5ae6ba/pkgs/applications/networking/cluster/kubernetes/kubectl.nix

I have never had any value set for `KUBERNETES_EXEC_INFO` and I'm not sure how the `kubectl` binary is expected to change that.

**Comment by weinong** [comment] 2022-11-17 17:46
@yurrriq your issue should be resolved by v0.0.22 release. give that a try. That being said, kubectl would have set `KUBERNETES_EXEC_INFO` env var. you may need to look into why your build acts differently than upstream kubectl

**Comment by everjing** [comment] 2022-11-17 19:19
> ```
> $ kubectl version --client
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"windows/amd64"}
> ```

@wiceywkus This issue is caused by using kubectl versions below 1.22.0, where "interactiveMode" is always set to "false" regardless of what you have configured. Upgrading to 1.22.0 or above will work and please let us know if you are able to do so or not. Also, we plan to change from failing directly to printing out warning first and then providing instructions for users to upgrade to 1.22.0 version or above of kubectl under the situation of "interactiveMode : Never" and "devicelogin" method.

**Comment by wiceywkus** [comment] 2022-11-17 21:12
Thank you @everjing.  kubectl v1.22.15 + kubelogin v.0.0.22 work as you stated.  Thank you!

**Comment by everjing** [comment] 2022-11-17 22:12
> Thank you @everjing. kubectl v1.22.15 + kubelogin v.0.0.22 work as you stated. Thank you!

@wiceywkus You are very welcome :) Thanks a lot for sharing your experience to help us make kubelogin more robust and efficient. Feel free to bring up comments/issues/concerns/suggestions anytime!

**Comment by everjing** [comment] 2022-11-18 16:54
@wiceywkus FYI kubelogin v.0.0.23 is released, which solves this issue for users whose kubectl versions below 1.22 without necessity to upgrade. Feel free to choose whatever version of kubectl you prefer and give it a try!

**Comment by wiceywkus** [comment] 2022-11-18 17:28
Oh the things you do for me... (flattered)
FYI, with Azure Kubelogin v0.0.23, I regression tested:
kubectl v1.20.15
kubectl v1.21.14
kubectl v1.22.15
All good with existing tokens.  I did not have to re-device login. 
I re-tested the Device Code Flow with v1.20.15.
Looks good to me.

**Comment by wiceywkus** [comment] 2022-11-18 18:26
So (pressing my luck), with the success above behind me, I moved onto OpenLens v6.2.0 (https://github.com/lensapp/lens/tree/v6.2.0) and now get:
```
Error: devicelogin is not supported if interactiveMode is 'never'
E1118 13:21:47.972352 25416 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubelogin failed with exit code 1
getting credentials: exec: executable kubelogin failed with exit code 1
```
Looks familiar. 
OpenLens uses `"@kubernetes/client-node": "^0.17.1"`, which is this one: https://www.npmjs.com/package/@kubernetes/client-node?activeTab=readme.

Should the compatibility support that is in v0.0.23 work with the Kubernetes JavaScript client? 
Is this a different issue?

**Comment by weinong** [comment] 2022-11-18 18:30
@wiceywkus even if you add `interactiveMode: IfAvailable`? seems like a bug in client-node

**Comment by wiceywkus** [comment] 2022-11-18 18:33
Let me check.
If I fall back to Kubelogin v0.0.20, it is ok.

**Comment by weinong** [comment] 2022-11-18 18:34
@wiceywkus with v0.0.23, can you add -v=10 in get-token args in kubeconfig, it will print out the KUBENETES_EXEC_INFO env var

**Comment by wiceywkus** [comment] 2022-11-18 18:48
Yes, even with `interactiveMode: IfAvailable` it fails.
-v=10 output from kubectl:
```
I1118 13:41:55.681152   24996 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 13:41:55.684913   24996 execCredentialPlugin.go:48] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<guid>_legacy.json
I1118 13:41:55.689449   24996 execCredentialPlugin.go:95] getting refresher
I1118 13:41:55.690749   24996 execCredentialPlugin.go:104] refresh token
I1118 13:41:56.543691   24996 execCredentialPlugin.go:114] token refreshed
```
That verbose output is not output by OpenLens by default.

**Comment by weinong** [comment] 2022-11-18 18:52
@wiceywkus if you cannot add verbose level, would it help if I provide a private build for debugging? if so, is it linux amd64?

**Comment by wiceywkus** [comment] 2022-11-18 19:04
OpenLens embeds binaries
Kubectl:
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"windows/amd64"}
`
lens-k8s-proxy included is here: https://github.com/lensapp/lens-k8s-proxy/tree/v0.2.1 
`{"gitVersion":"v0.2.1","gitCommit":"ad18e7e5f5eb9610c3279b88cf1922ac4092adb6"}`
`module github.com/lensapp/lens-k8s-proxy

go 1.17

require (
	k8s.io/cli-runtime v0.23.4
	k8s.io/client-go v0.23.4
	k8s.io/klog/v2 v2.40.1
	k8s.io/kubectl v0.23.4
)`

**Comment by weinong** [comment] 2022-11-18 19:28
you can download from this link: `https://kubelogintest.blob.core.windows.net/container/kubelogin.exe?sp=r&st=2022-11-18T19:25:59Z&se=2022-11-21T03:25:59Z&spr=https&sv=2021-06-08&sr=b&sig=1QRDBvC0A4PbLtQd0D6PbBfgcJZBRHhtB2dC97EQuhU%3D` let me know what it prints out

**Comment by wiceywkus** [comment] 2022-11-18 19:34
output:
```
I1118 14:31:17.561464   21936 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 14:31:17.566043   21936 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:31:17.569929   21936 execCredentialPlugin.go:89] access token is still valid. will return
I1118 14:31:17.989734   12600 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 14:31:17.993538   12600 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:31:17.996946   12600 execCredentialPlugin.go:89] access token is still valid. will return
I1118 14:31:18.416177   24700 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 14:31:18.420077   24700 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:31:18.423453   24700 execCredentialPlugin.go:89] access token is still valid. will return
I1118 14:31:18.863255    5004 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 14:31:18.867028    5004 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:31:18.870419    5004 execCredentialPlugin.go:89] access token is still valid. will return
I1118 14:31:19.290783   11188 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
I1118 14:31:19.293994   11188 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:31:19.297348   11188 execCredentialPlugin.go:89] access token is still valid. will return
Unable to connect to the server: getting credentials: decoding stdout: yaml: line 3: could not find expected ':'
```

**Comment by wiceywkus** [comment] 2022-11-18 19:35
Line 3 in my kubeconfig is:
`- cluster:`

**Comment by weinong** [comment] 2022-11-18 19:36
is this the failing one? it looks like a working one

**Comment by wiceywkus** [comment] 2022-11-18 19:37
If I replace kubelogin v0.0.23 with the debug version, then it aborts:
`Unable to connect to the server: getting credentials: decoding stdout: yaml: line 3: could not find expected ':'`

**Comment by weinong** [comment] 2022-11-18 19:38
oh crap, i printed that to stdout, which is why. let me rebuild it.

**Comment by weinong** [comment] 2022-11-18 19:44
try this again: `https://kubelogintest.blob.core.windows.net/container/kubelogin.exe?sp=r&st=2022-11-18T19:42:57Z&se=2022-11-21T03:42:57Z&spr=https&sv=2021-06-08&sr=b&sig=AZL0dgvlc%2BYu9ATp066GCKt7fILVkIpxgyrpzxoXfOY%3D`

**Comment by wiceywkus** [comment] 2022-11-18 20:00
kubectl execution successful:
```
I1118 14:55:24.786910   21464 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}
KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":true}}

I1118 14:55:24.795038   21464 execCredentialPlugin.go:49] Login Method: devicecode, Environment: AzurePublicCloud, TenantID: <tenantid>, ServerID: <serverid>, ClientID: <clientid>, IsLegacy: true, msiResourceID: , tokenCacheDir: C:\Users\wiceywkus/.kube/cache/kubelogin/, tokenCacheFile: C:\Users\wiceywkus\.kube\cache\kubelogin\AzurePublicCloud-<serverid>-<clientid>-<tenantid>_legacy.json
I1118 14:55:24.799599   21464 execCredentialPlugin.go:89] access token is still valid. will return
```
same output with OpenLens' embedded kubectl version 
with OpenLens running, I get:
```
I1118 14:59:09.228622 24656 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":false}}
KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":false}}

Error: devicelogin is not supported if interactiveMode is 'never'
E1118 14:59:09.259596 21748 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubelogin failed with exit code 1
getting credentials: exec: executable kubelogin failed with exit code 1
I1118 14:59:35.970642 21388 execCredentialPlugin.go:41] KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":false}}
KUBERNETES_EXEC_INFO is: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{"interactive":false}}

Error: devicelogin is not supported if interactiveMode is 'never'
E1118 14:59:35.990997 21748 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubelogin failed with exit code 1
getting credentials: exec: executable kubelogin failed with exit code 1
```

**Comment by weinong** [comment] 2022-11-18 20:39
i think i

**Comment by wiceywkus** [comment] 2022-11-18 20:48
The OpenLens "Kubernetes Client" is running in a proxy inside NodeJS (lens-k8s-proxy).  So, in its context, no it is not interactive.  But then how will it work? 
BTW: Kubelogin v0.0.20 works.

**Comment by weinong** [comment] 2022-11-18 22:03
@wiceywkus so you are saying you have been relying on lens-k8s-proxy to put the token in the cache?

**Comment by weinong** [comment] 2022-11-18 22:06
v0.0.20 works because we added this extra check since v0.0.21. I reverted this change and will cut a new release soon.

**Closed** 2022-11-19 00:19 UTC
