### ISSUE TITLE
Is there existing work to switch kubelogin from MS ADAL to MSAL library

### ISSUE THREAD

**Issue by wiceywkus** [Azure/kubelogin#77] opened 2022-02-03 17:39 UTC
With the MS ADAL library going out of support in June, is there work already underway by someone to switch from the ADAL to the MSAL libraries?

**Comment by weinong** [comment] 2022-02-03 23:26
This is on our radar. That being said, it's mostly waiting for the readiness of azure sdk for go + msal for go, which hasn't been fully integrated yet last time I checked.

**Comment by weinong** [comment] 2022-02-04 01:49
hmm, looks like msal for go is integrated now https://github.com/Azure/azure-sdk-for-go/issues/14920

**Comment by wiceywkus** [comment] 2022-02-04 13:37
Check out this library: https://github.com/AzureAD/microsoft-authentication-library-for-go

**Comment by weinong** [comment] 2022-02-04 19:39
https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/58
https://github.com/Azure/azure-sdk-for-go/issues/6602#issuecomment-1030290807

**Comment by weinong** [comment] 2022-02-04 19:40
closing this as a dupe of #62

**Closed by weinong** 2022-02-04 19:40 UTC
